name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies (workspaces)
        run: npm ci

      - name: Build all packages
        run: npm run build

      - name: Upload backend dist
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist-node-${{ matrix.node }}
          path: packages/backend/dist
          if-no-files-found: ignore

      - name: Upload frontend dist
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist-node-${{ matrix.node }}
          path: |
            packages/frontend/dist/**
          if-no-files-found: ignore

  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Lint backend
        run: npm run lint --workspace=@jardinier/backend

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Test backend
        run: npm test --workspace=@jardinier/backend -- --ci
