name: Deploy Backend (Render)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    paths:
      - 'packages/backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy via hook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "RENDER_DEPLOY_HOOK secret is not set. Add it in GitHub repo settings > Secrets and variables > Actions" >&2
            exit 1
          fi
          echo "Calling Render deploy hook..."
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
